### ISSUE TITLE
Can it worked with Switch update 13.0.0

### ISSUE THREAD

**Issue by day210** [Poohl/joycontrol#11]
Can it worked with Switch update 13.0.0

**Comment by lowlevel-1989** [comment]
automatic reconnection prototype
worked with https://github.com/formatcom/joytransfer

NINTENDO SWITCH
- version 12.1.0
- version 13.0.0

DEMO:
https://www.youtube.com/watch?v=GBxLCyi0jz8

connect joycon after sync cause disconnection
https://www.youtube.com/watch?v=XbHErgeM34E
