### ISSUE TITLE
Connection lost immediately after starting Amiibo read after firmware update 12.0.0

### ISSUE THREAD

**Issue by system-** [Poohl/joycontrol#2]
```
[11:05:15] joycontrol.transport read::81 ERROR - No data received.
[11:05:15] joycontrol.protocol connection_lost::124 ERROR - Connection lost.
[11:05:15] asyncio default_exception_handler::1707 ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<L2CAP_Transport.close() done, defined at /home/soli/joycon/joycontrol/transport.py:148> exception=AttributeError("'NoneType' object has no attribute 'cancel'")>

```

**Comment by Poohl** [comment]
Yeah, bad news for now. While we have a way and means to pair and connect to the switch in V12 by now, we don't know what or why it disconnects when changing input mode. NXBT is suspecting the polling rate, I am resarching the timing-byte and it might me neither of the two...

**Comment by Poohl** [comment]
Have you had any more success? It seems to be somewhat hardware related so what Bluetooth chipset are you using?

**Comment by Poohl** [comment]
@system- @thxomas @yamakaky
I found a way to get past the 'rcvd max slots change' thing: The switch will not disconnect unless you send something wrong, so just don't send anything and wait for the `Max Slots Change` or whatever it actually is (i just waited until i got the writer restarted XD, bc it crashed).
Afterwards you can simply continue sending input as usual and the switch will start sending you the NFC-subcommands.
Will work on automating this after the pairing is working again. The main problem is getting anywhere without sending input (i used the touchscreen, doesn't work in game).

**Comment by Poohl** [comment]
Please check out [this comment](https://github.com/Poohl/joycontrol/issues/3#issuecomment-834791031)

**Comment by Poohl** [comment]
And try the latest version. I had no issues reading an amiibo. Didn't disconnect or anything.

**Comment by Poohl** [comment]
Ok, also consider this closed, as I can read and write amiibos.

If the issue persists please open a new issue, to be sure that either the V12 fix isn't working or the problem is not V12.

**Comment by system-** [comment]
EPIC
