### ISSUE TITLE
NFC(Amiibo) function not work on switch ver. 14.0.0+

### ISSUE THREAD

**Issue by 8ar10der** [Poohl/joycontrol#22]
I believe the Amiibo emulation is not work for the system version 14. 
I can pair and the button command can be send and work.
But when I try to write nfc in the CLI.
I just can get a message "added nfc content" but nothing happend on my Switch.
So sad. I hate Nintendo's updates. :(

**Comment by jerryc20** [comment]
same，did u find out how to solve with that? help me plz
