### ISSUE TITLE
Feature Request: Wake up Switch from sleep mode

### ISSUE THREAD

**Issue by kindfulkirby** [Poohl/joycontrol#8]
I don't know if that's possible. The real Pro Controller can do that, most 3rd party controllers seemingly can't.

**Comment by Poohl** [comment]
The short answer: No.
The long answer: This wakeup is an extension to the chips by the chipvendor Broadcom (I belive, might be mistakan on the vendor) that doesn't actually use bluetooth itself, just the same frequency space. So this is very possible, if you have a supported chip by these guys and some kind of documentaion on how it works.
Also look at [Nintendo_Switch_Reverse_Engineering #103](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/issues/103)

**Comment by kindfulkirby** [comment]
That makes sense, thanks!
